apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: spartacus-processing-
spec:
  entrypoint: main
  securityContext:
    runAsUser: 74268
    fsGroup: 71473
  volumes:
    - name: eodc-mount
      persistentVolumeClaim:
        claimName: eodc-nfs-claim

  templates:
    - name: main
      steps:
        - - name: spartacus-parallel
            template: spartacus-pipeline
            arguments:
              parameters:
                - name: var
                  value: "{{item}}"
            withParam: '["TX", "TN", "RR", "SA"]'

    - name: spartacus-pipeline
      inputs:
        parameters:
          - name: var
      steps:
        - - name: download-data
            template: download
            arguments:
              parameters:
                - name: var
                  value: "{{inputs.parameters.var}}"
        - - name: process-data
            template: process
            arguments:
              parameters:
                - name: var
                  value: "{{inputs.parameters.var}}"
              artifacts:
                - name: spartacus-file
                  from: "{{steps.download-data.outputs.artifacts.spartacus-file}}"

    - name: download
      inputs:
        parameters:
          - name: var
      container:
        image: ghcr.io/katharinastarzer21/image_zarr:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["spartacus_download.py", "{{inputs.parameters.var}}"]
      outputs:
        artifacts:
          - name: inca-file
            path: "/tmp/SPARTACUS2-DAILY_{var}_2025.nc"
            archive:
              none: {}

    - name: process
      inputs:
        parameters:
          - name: var
        artifacts:
          - name: inca-file
            path: "/tmp/SPARTACUS2-DAILY_{var}_2025.nc"
      container:
        image: ghcr.io/katharinastarzer21/image_zarr:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["spartacus_write.py", "{{inputs.parameters.var}}"]
        volumeMounts:
          - name: eodc-mount
            mountPath: /eodc